### ISSUE TITLE
Cannot download `npm` dependencies.

### ISSUE THREAD

**Issue by caquino** [actions/go-dependency-submission#17]
Hi,

I'm opening this issue to double-check if this is expected, but it is not possible to clone this repository and execute `npm install`, either directly on the local machine, or on the devcontainer as it requires credentials to retrieve `github/dependency-submission-toolkit`

I've also opened an issue at dependency-submission-toolkit to clarify the issue. https://github.com/github/dependency-submission-toolkit/issues/14

**Comment by lseppala** [comment]
Cross-posting [my answer on the toolkit repo](https://github.com/github/dependency-submission-toolkit/issues/14#issuecomment-1167977849): 

> you can authenticate by running the following your project directory:
> ```
> npm login --scope=@github --registry=https://npm.pkg.github.com
> ```
> Your username is your GitHub username, and your password will be a personal access token ([instructions on how to create here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)) with at least the 'read:packages' authorization.
 
This has been added to the Readme.

Apologies for this temporary workaround while we get the library published to npmjs.org.
